% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={STA 5207: Homework 6},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{STA 5207: Homework 6}
\author{}
\date{\vspace{-2.5em}Due: Friday, March 1 by 11:59 PM}

\begin{document}
\maketitle

Include your R code in an R chunks as part of your answer. In addition,
your written answer to each exercise should be self-contained so that
the grader can determine your solution without reading your code or
deciphering its output.

\hypertarget{exercise-1-diagnostics-for-teenage-gambling-data-40-points}{%
\subsection{Exercise 1 (Diagnostics for Teenage Gambling Data) {[}40
points{]}}\label{exercise-1-diagnostics-for-teenage-gambling-data-40-points}}

For this exercise we will use the \texttt{teengamb} data set from the
\texttt{faraway} package. You can also find that data in
\texttt{teengamb.csv} on Canvas. You can use \texttt{?teengamb} to learn
about the data set. The variables in the data set are

\begin{itemize}
\tightlist
\item
  \texttt{sex}: 0 = male, 1 = female.
\item
  \texttt{status}: Socioeconomic status score based on parents'
  occupation.
\item
  \texttt{income}: in pounds per week.
\item
  \texttt{verbal}: verbal score in words out of 12 correctly defined.
\item
  \texttt{gamble}: expenditure on gambling in pounds per year.
\end{itemize}

In the following exercise, use \texttt{gamble} as the response and the
other variables as predictors. Some of these questions are subjective,
so there may not be a ``right'' answer. Just make sure to justify your
answer based on the plots and statistical tests.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  (8 points) Check the constant variance assumption for this model using
  a graphical method and a hypothesis test at the \(\alpha = 0.05\)
  significance level. Do you feel it has been violated? Justify your
  answer. Include any plots in your response.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(}\StringTok{\textquotesingle{}faraway\textquotesingle{}}\NormalTok{)}
\FunctionTok{library}\NormalTok{(}\StringTok{\textquotesingle{}lmtest\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: zoo
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'zoo'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     as.Date, as.Date.numeric
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(teengamb, }\AttributeTok{package=}\StringTok{\textquotesingle{}faraway\textquotesingle{}}\NormalTok{)}
\NormalTok{model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(gamble }\SpecialCharTok{\textasciitilde{}}\NormalTok{ sex }\SpecialCharTok{+}\NormalTok{ status }\SpecialCharTok{+}\NormalTok{ income }\SpecialCharTok{+}\NormalTok{ verbal, }\AttributeTok{data=}\NormalTok{teengamb)}
\FunctionTok{plot}\NormalTok{(model, }\AttributeTok{which=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

  \includegraphics{Homework6_files/figure-latex/unnamed-chunk-1-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{bptest}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  studentized Breusch-Pagan test
## 
## data:  model
## BP = 6.4288, df = 4, p-value = 0.1693
\end{verbatim}

  \textbf{Answer:} Since the p-value is 0.169 which is greater than our
  significance level, we do not reject the null hypothesis at the 0.05
  significance level and determine that the constant variance assumption
  is not violated.
\item
  (8 points) Check the normality assumption using a Q-Q plot and a
  hypothesis test at the \(\alpha = 0.05\) significance level. Do you
  feel it has been violated? Justify your answer. Include any plots in
  your response.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(}\StringTok{\textquotesingle{}olsrr\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'olsrr'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:faraway':
## 
##     hsb
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:datasets':
## 
##     rivers
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ols\_plot\_resid\_qq}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

  \includegraphics{Homework6_files/figure-latex/unnamed-chunk-2-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{resid}\NormalTok{(model))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  resid(model)
## W = 0.86839, p-value = 8.16e-05
\end{verbatim}

  \textbf{Answer:} Since our Shapiro-Wilk test resulted in a p-value of
  less than 0.05, we do reject the null hypothesis and say the normality
  assumption has been violated.
\item
  (5 points) Check for any high leverage points. Report any observations
  you determine to have high leverage.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{which}\NormalTok{(}\FunctionTok{hatvalues}\NormalTok{(model) }\SpecialCharTok{\textgreater{}} \DecValTok{2} \SpecialCharTok{*} \FunctionTok{mean}\NormalTok{(}\FunctionTok{hatvalues}\NormalTok{(model)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 31 33 35 42 
## 31 33 35 42
\end{verbatim}

  \textbf{Answer:} We see there to be 4 observations (31, 33, 35, and
  42) which have high leverage points.
\item
  (5 points) Check for any outliers in the data set at the
  \(\alpha = 0.05\) significance level. Report any observations you
  determine to be outliers.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{outlier\_test\_cutoff }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(model, }\AttributeTok{alpha =} \FloatTok{0.05}\NormalTok{) \{}
\NormalTok{    n }\OtherTok{=} \FunctionTok{length}\NormalTok{(}\FunctionTok{resid}\NormalTok{(model))}
    \FunctionTok{qt}\NormalTok{(alpha}\SpecialCharTok{/}\NormalTok{(}\DecValTok{2} \SpecialCharTok{*}\NormalTok{ n), }\AttributeTok{df =} \FunctionTok{df.residual}\NormalTok{(model) }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{, }\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{\}}
\NormalTok{cutoff }\OtherTok{=} \FunctionTok{outlier\_test\_cutoff}\NormalTok{(model, }\AttributeTok{alpha =} \FloatTok{0.05}\NormalTok{)}
\FunctionTok{which}\NormalTok{(}\FunctionTok{abs}\NormalTok{(}\FunctionTok{rstudent}\NormalTok{(model)) }\SpecialCharTok{\textgreater{}}\NormalTok{ cutoff)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 24 
## 24
\end{verbatim}

  \textbf{Answer:} We see one outlier at observation 24.
\item
  (5 points) Check for any highly influential points in the data set.
  Report any observations your determine are highly influential.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{which}\NormalTok{(}\FunctionTok{cooks.distance}\NormalTok{(model) }\SpecialCharTok{\textgreater{}} \DecValTok{4} \SpecialCharTok{/} \FunctionTok{length}\NormalTok{(}\FunctionTok{cooks.distance}\NormalTok{(model)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 24 39 
## 24 39
\end{verbatim}

  \textbf{Answer:} We see that observations 24 and 39 are highly
  influential points in the data set after using Cook's distance.
\item
  (9 points) Fit a model with the high influence points you found in the
  previous question removed. Perform a hypothesis test at the
  \(\alpha = 0.05\) significance level to check the normality
  assumption. What do you conclude?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{noninfluential\_ids }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(}
    \FunctionTok{cooks.distance}\NormalTok{(model) }\SpecialCharTok{\textless{}=} \DecValTok{4} \SpecialCharTok{/} \FunctionTok{length}\NormalTok{(}\FunctionTok{cooks.distance}\NormalTok{(model)))}
\NormalTok{model\_fix }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(gamble }\SpecialCharTok{\textasciitilde{}}\NormalTok{ sex }\SpecialCharTok{+}\NormalTok{ status }\SpecialCharTok{+}\NormalTok{ income }\SpecialCharTok{+}\NormalTok{ verbal, }
               \AttributeTok{data=}\NormalTok{teengamb,}
               \AttributeTok{subset =}\NormalTok{ noninfluential\_ids)}
\FunctionTok{ols\_plot\_resid\_qq}\NormalTok{(model\_fix)}
\end{Highlighting}
\end{Shaded}

  \includegraphics{Homework6_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{resid}\NormalTok{(model\_fix))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  resid(model_fix)
## W = 0.96728, p-value = 0.23
\end{verbatim}

  \textbf{Answer:} Upon removing the influential points, the p-value of
  our test to check the normality assumption is far greater than our
  significance level of 0.05. Therefore, we do not rejecct the null
  hypothesis and conclude that the normality assumption has not been
  violated.
\end{enumerate}

\hypertarget{exercise-2-add-variable-plots-for-the-teenage-gambling-data-20-points}{%
\subsection{Exercise 2 (Add Variable Plots for the Teenage Gambling
Data) {[}20
points{]}}\label{exercise-2-add-variable-plots-for-the-teenage-gambling-data-20-points}}

For this exercise, we will also use the \texttt{teengamb} data set from
the \texttt{faraway} package. Some of these questions are subjective, so
there may not be a ``right'' answer. Just make sure to justify your
answer based on the plots and statistical tests.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  (8 points) Fit a multiple linear regression model with \texttt{gamble}
  as the response and the other four variables as predictors. Obtain the
  partial regression plots. For each predictor, determine if it appears
  to have a linear relationship with the response after removing the
  effects of the other predictors based on these plots. Include the
  plots in your response.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(gamble }\SpecialCharTok{\textasciitilde{}}\NormalTok{ sex }\SpecialCharTok{+}\NormalTok{ status }\SpecialCharTok{+}\NormalTok{ income }\SpecialCharTok{+}\NormalTok{ verbal, }\AttributeTok{data=}\NormalTok{teengamb)}
\FunctionTok{ols\_plot\_added\_variable}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
## `geom_smooth()` using formula = 'y ~ x'
## `geom_smooth()` using formula = 'y ~ x'
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

  \includegraphics{Homework6_files/figure-latex/unnamed-chunk-7-1.pdf}

  \textbf{Answer:} It looks like all predictors have a linear
  relationship with ``gamble'' after removing the effects of the other
  predictors.
\item
  (8 points) Fit the following two models and obtain their residuals:

  \begin{itemize}
  \tightlist
  \item
    Model 1: \texttt{gamble} \textasciitilde{} \texttt{verbal} +
    \texttt{status} + \texttt{sex}.
  \item
    Model 2: \texttt{income} \textasciitilde{} \texttt{verbal} +
    \texttt{status} + \texttt{sex}.
  \end{itemize}

  Next fit a simple linear regression model with the residuals of Model
  1 as the response and the residuals of Model 2 as the predictor.
  Report the value of the slope parameter.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model1 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(gamble }\SpecialCharTok{\textasciitilde{}}\NormalTok{ verbal }\SpecialCharTok{+}\NormalTok{ status }\SpecialCharTok{+}\NormalTok{ sex, }\AttributeTok{data=}\NormalTok{teengamb)}
\NormalTok{model2 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(income }\SpecialCharTok{\textasciitilde{}}\NormalTok{ verbal }\SpecialCharTok{+}\NormalTok{ status }\SpecialCharTok{+}\NormalTok{ sex, }\AttributeTok{data=}\NormalTok{teengamb)}

\NormalTok{model3 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(}\FunctionTok{resid}\NormalTok{(model1) }\SpecialCharTok{\textasciitilde{}} \FunctionTok{resid}\NormalTok{(model2))}
\NormalTok{model3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = resid(model1) ~ resid(model2))
## 
## Coefficients:
##   (Intercept)  resid(model2)  
##    -2.280e-16      4.962e+00
\end{verbatim}

  \textbf{Answer:} The value of the slope parameter of the model with
  the residuals of model 1 as the response and the residuals of model 2
  as the predictor is 4.962.
\item
  (4 points) Compare the coefficient of \texttt{income} from the model
  fit in part 1 (\texttt{gamble} \textasciitilde{} \texttt{verabal} +
  \texttt{status} + \texttt{sex} + \texttt{income}) to the value of the
  slope parameter in part 2. Are their values the same or different?

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{coef}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  (Intercept)          sex       status       income       verbal 
##  22.55565063 -22.11833009   0.05223384   4.96197922  -2.95949350
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{coef}\NormalTok{(model3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   (Intercept) resid(model2) 
## -2.279512e-16  4.961979e+00
\end{verbatim}

  \textbf{Answer:} These values are the same, both at 4.961979.
\end{enumerate}

\hypertarget{exercise-3-diagnostics-for-swiss-fertility-data-40-points}{%
\subsection{Exercise 3 (Diagnostics for Swiss Fertility Data) {[}40
points{]}}\label{exercise-3-diagnostics-for-swiss-fertility-data-40-points}}

For this exercise we will use the \texttt{swiss} data set from the
\texttt{faraway} package. You can also find the data in
\texttt{swiss.csv} on Canvas. You can use \texttt{?swiss} to learn about
the data set. The variables in the data set are

\begin{itemize}
\tightlist
\item
  \texttt{Fertility}: a `common standardized fertility measure'.
\item
  \texttt{Agriculture}: proportion of males involved in agriculture as
  an occupation.
\item
  \texttt{Examination}: proportion of draftees receiving the highest
  mark on army examination.
\item
  \texttt{Education}: proportion with education beyond primary school
  for draftees.
\item
  \texttt{Catholic}: proportion `catholic' (as opposed to `protestant').
\item
  \texttt{Infant.Mortality}: proportion of live births who live less
  than 1 year.
\end{itemize}

In the following exercise, use \texttt{Fertility} as the response and
the other variables as predictors. Some of these questions are
subjective, so there may not be a ``right'' answer. Just make sure to
justify your answer based on the plots and statistical tests.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  (8 points) Check the constant variance assumption for this model using
  a graphical method and a hypothesis test at the \(\alpha = 0.05\)
  significance level. Do you feel it has been violated? Justify your
  answer. Include any plots in your response.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(swiss)}
\NormalTok{model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(Fertility }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data=}\NormalTok{swiss)}
\FunctionTok{plot}\NormalTok{(model, }\AttributeTok{which=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

  \includegraphics{Homework6_files/figure-latex/unnamed-chunk-10-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{bptest}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  studentized Breusch-Pagan test
## 
## data:  model
## BP = 5.8511, df = 5, p-value = 0.321
\end{verbatim}

  \textbf{Answer:} Since the p-value is .321 which is greater than our
  significance level, we do not reject the null hypothesis at the 0.05
  significance level and determine that the constant variance assumption
  is not violated.
\item
  (8 points) Check the normality assumption using a Q-Q plot and a
  hypothesis test at the \(\alpha = 0.05\) significance level. Do you
  feel it has been violated? Justify your answer. Include any plots in
  your response.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ols\_plot\_resid\_qq}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

  \includegraphics{Homework6_files/figure-latex/unnamed-chunk-11-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{resid}\NormalTok{(model))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  resid(model)
## W = 0.98892, p-value = 0.9318
\end{verbatim}

  \textbf{Answer:} Since our Shapiro-Wilk test resulted in a p-value of
  more than 0.05, we do not reject the null hypothesis and say the
  normality assumption has not been violated.
\item
  (4 points) Check for any high leverage points. Report any observations
  you determine to have high leverage.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{which}\NormalTok{(}\FunctionTok{hatvalues}\NormalTok{(model) }\SpecialCharTok{\textgreater{}} \DecValTok{2} \SpecialCharTok{*} \FunctionTok{mean}\NormalTok{(}\FunctionTok{hatvalues}\NormalTok{(model)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    La Vallee V. De Geneve 
##           19           45
\end{verbatim}

  \textbf{Answer:} We observe leverage points at La Vallee and V. De
  Geneve
\item
  (4 points) Check for any outliers in the data set at the
  \(\alpha = 0.05\) significance level. Report any observations you
  determine to be outliers.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{outlier\_test\_cutoff }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(model, }\AttributeTok{alpha =} \FloatTok{0.05}\NormalTok{) \{}
\NormalTok{    n }\OtherTok{=} \FunctionTok{length}\NormalTok{(}\FunctionTok{resid}\NormalTok{(model))}
    \FunctionTok{qt}\NormalTok{(alpha}\SpecialCharTok{/}\NormalTok{(}\DecValTok{2} \SpecialCharTok{*}\NormalTok{ n), }\AttributeTok{df =} \FunctionTok{df.residual}\NormalTok{(model) }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{, }\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{\}}
\NormalTok{cutoff }\OtherTok{=} \FunctionTok{outlier\_test\_cutoff}\NormalTok{(model, }\AttributeTok{alpha =} \FloatTok{0.05}\NormalTok{)}
\FunctionTok{which}\NormalTok{(}\FunctionTok{abs}\NormalTok{(}\FunctionTok{rstudent}\NormalTok{(model)) }\SpecialCharTok{\textgreater{}}\NormalTok{ cutoff)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## named integer(0)
\end{verbatim}

  \textbf{Answer:} We see no outliers in the data set.
\item
  (4 points) Check for any highly influential points in the data set.
  Report any observations your determine are highly influential.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{which}\NormalTok{(}\FunctionTok{cooks.distance}\NormalTok{(model) }\SpecialCharTok{\textgreater{}} \DecValTok{4} \SpecialCharTok{/} \FunctionTok{length}\NormalTok{(}\FunctionTok{cooks.distance}\NormalTok{(model)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Porrentruy      Sierre   Neuchatel Rive Droite Rive Gauche 
##           6          37          42          46          47
\end{verbatim}

  \textbf{Answer:} We see 5 outliers in the data set at observations
  Porrentruy, Sierre, Neuchatel, Rive Droitte, and Rive Gauche.
\item
  (6 points) Compare the regression coefficients including and excluding
  the influential observations. Comment on the difference between these
  two sets of coefficients.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{coef}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      (Intercept)      Agriculture      Examination        Education 
##       66.9151817       -0.1721140       -0.2580082       -0.8709401 
##         Catholic Infant.Mortality 
##        0.1041153        1.0770481
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{noninfluential\_ids }\OtherTok{=} \FunctionTok{which}\NormalTok{(}
    \FunctionTok{cooks.distance}\NormalTok{(model) }\SpecialCharTok{\textless{}=} \DecValTok{4} \SpecialCharTok{/} \FunctionTok{length}\NormalTok{(}\FunctionTok{cooks.distance}\NormalTok{(model)))}

\CommentTok{\# fit the model on non{-}influential subset}
\NormalTok{model\_fix }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Fertility }\SpecialCharTok{\textasciitilde{}}\NormalTok{ .,}
               \AttributeTok{data =}\NormalTok{ swiss,}
               \AttributeTok{subset =}\NormalTok{ noninfluential\_ids)}

\CommentTok{\# return coefficients}
\FunctionTok{coef}\NormalTok{(model\_fix)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      (Intercept)      Agriculture      Examination        Education 
##      66.44458475      -0.21819812      -0.50016393      -0.69046520 
##         Catholic Infant.Mortality 
##       0.09846806       1.35767263
\end{verbatim}

  \textbf{Answer:} The intercepts, and coefficients for agriculture look
  pretty similar to each other, where as the other predictors have
  pretty different coefficient values.
\item
  (6 points) Compare the predictions at the highly influential
  observations based on a model that includes and excludes the
  influential observations. Comment on the difference between these two
  sets of predictions.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{influential\_obs }\OtherTok{=} \FunctionTok{subset}\NormalTok{(}
\NormalTok{    swiss, }\FunctionTok{cooks.distance}\NormalTok{(model) }\SpecialCharTok{\textgreater{}} \DecValTok{4} \SpecialCharTok{/} \FunctionTok{length}\NormalTok{(}\FunctionTok{cooks.distance}\NormalTok{(model)))}
\FunctionTok{predict}\NormalTok{(model, influential\_obs)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Porrentruy      Sierre   Neuchatel Rive Droite Rive Gauche 
##    90.50011    76.87869    53.51934    54.36209    58.07426
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{predict}\NormalTok{(model\_fix, influential\_obs)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Porrentruy      Sierre   Neuchatel Rive Droite Rive Gauche 
##    94.43980    76.33683    55.89622    57.92582    61.32012
\end{verbatim}

  \textbf{Answer:} The predictions for Sierre doesn't change nearly at
  all, but the rest of the observations change quite a bit between the
  two models.
\end{enumerate}

\end{document}
